# Generated by Django 6.0.1 on 2026-01-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, choices=[('1', '1-sinf'), ('2', '2-sinf'), ('3', '3-sinf'), ('4', '4-sinf'), ('5', '5-sinf'), ('6', '6-sinf'), ('7', '7-sinf'), ('8', '8-sinf'), ('9', '9-sinf'), ('10', '10-sinf'), ('11', '11-sinf'), ('STUDENT', 'Talaba'), ('GRADUATE', 'Bitiruvchi')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
