# Generated by Django 6.0.1 on 2026-01-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_birth_date_user_grade_user_region_user_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=255)),
                ('admin_chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot Configuration',
                'verbose_name_plural': 'Bot Configurations',
                'db_table': 'bot_configs',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_linking_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
