# Generated by Django 6.0.1 on 2026-01-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('xp_threshold', models.IntegerField(help_text='XP required to reach this level')),
                ('reward_description', models.CharField(max_length=255)),
                ('icon', models.CharField(default='Award', help_text='Lucide icon name', max_length=50)),
            ],
            options={
                'db_table': 'level_rewards',
                'ordering': ['level'],
            },
        ),
        migrations.AddField(
            model_name='olympiad',
            name='xp_reward',
            field=models.IntegerField(default=50, help_text='XP given for participation'),
        ),
    ]
