# Generated by Django 6.0.1 on 2026-01-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_levelreward_olympiad_xp_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='xp_reward',
            field=models.IntegerField(default=50, help_text='XP given upon completion'),
        ),
    ]
