# Generated by Django 6.0.1 on 2026-01-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_activitylog_userstreak'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Olimpiadalar orqali kelajagingizni quring', max_length=200)),
                ('hero_subtitle', models.TextField(default="O'zbekistonning eng iqtidorli yoshlari safida bo'ling. Bilimingizni sinang va qimmatbaho sovg'alarga ega bo'ling.")),
                ('hero_button_text', models.CharField(default='Boshlash', max_length=50)),
                ('hero_button_link', models.CharField(default='/register', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('show_stats', models.BooleanField(default=True)),
                ('stats_students', models.IntegerField(default=15000)),
                ('stats_olympiads', models.IntegerField(default=120)),
                ('stats_winners', models.IntegerField(default=450)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Configuration',
                'verbose_name_plural': 'Homepage Configuration',
                'db_table': 'homepage_config',
            },
        ),
        migrations.AddField(
            model_name='olympiad',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in homepage carousel'),
        ),
    ]
