# Generated by Django 6.0.1 on 2026-01-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_homepageconfig_olympiad_is_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageConfig',
        ),
        migrations.RemoveField(
            model_name='olympiad',
            name='is_featured',
        ),
    ]
