# Generated by Django 6.0.1 on 2026-01-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_homepageconfig_remove_olympiad_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'home_advantages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomePageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Olimpiadalar orqali kelajagingizni quring', max_length=200)),
                ('hero_subtitle', models.TextField(default="O'zbekistonning eng iqtidorli yoshlari safida bo'ling. Bilimingizni sinang va qimmatbaho sovg'alarga ega bo'ling.")),
                ('hero_button_text', models.CharField(default='Boshlash', max_length=50)),
                ('hero_button_link', models.CharField(default='/register', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('cta_title', models.CharField(default='Kelajagingizni bugundan boshlang', max_length=200)),
                ('cta_subtitle', models.TextField(default="Minglab o'quvchilar safida bo'ling va o'z bilimingizni sinovdan o'tkazing")),
                ('cta_button_text', models.CharField(default="Ro'yxatdan o'tish", max_length=50)),
                ('cta_button_link', models.CharField(default='/register', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Configuration',
                'verbose_name_plural': 'Homepage Configuration',
                'db_table': 'homepage_config',
            },
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'home_stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'home_steps',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='home_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='home_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
