# Generated by Django 6.0.1 on 2026-01-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_homeadvantage_homepageconfig_homestat_homestep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='BookOpen', help_text='Lucide icon name', max_length=50)),
                ('color', models.CharField(default='bg-blue-600', help_text='Tailwind class', max_length=50)),
                ('xp_reward', models.IntegerField(default=50)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['order', 'name'],
            },
        ),
    ]
