# Generated by Django 6.0.1 on 2026-01-27 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_teacherprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('STREAK', 'Streak Warning'), ('LESSON', 'Lesson Reminder'), ('OLYMPIAD', 'Olympiad Alert'), ('SYSTEM', 'System Message'), ('PAYMENT', 'Payment Update'), ('ACHIEVEMENT', 'Achievement Unlocked')], default='SYSTEM', max_length=20)),
                ('channel', models.CharField(choices=[('WEB', 'Web Only'), ('TELEGRAM', 'Telegram Only'), ('SMS', 'SMS Only'), ('ALL', 'All Channels')], default='WEB', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, help_text='Link to redirect user', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
