# Generated by Django 6.0.1 on 2026-01-27 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='Briefcase', help_text='Lucide icon name', max_length=50)),
                ('color', models.CharField(default='bg-indigo-600', help_text='Tailwind class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'professions',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionRoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('step_type', models.CharField(choices=[('LEARN', "O'rganish"), ('PRACTICE', 'Amaliyot'), ('COMPETE', 'Olimpiada'), ('CERTIFY', 'Sertifikat')], default='LEARN', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_steps', to='api.profession')),
            ],
            options={
                'db_table': 'profession_roadmap_steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField(default=3, help_text='1-5 stars')),
                ('order', models.IntegerField(default=0)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_subjects', to='api.profession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
            options={
                'db_table': 'profession_subjects',
                'ordering': ['order'],
                'unique_together': {('profession', 'subject')},
            },
        ),
    ]
