# Generated by Django 6.0.1 on 2026-01-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_profession_professionroadmapstep_professionsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='cannot_go_back',
            field=models.BooleanField(default=False, help_text='Prevent going back to previous questions'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='format',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('LIVE', 'Live'), ('HYBRID', 'Hybrid')], default='ONLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='is_random',
            field=models.BooleanField(default=False, help_text='Randomize question order'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='level',
            field=models.CharField(choices=[('BEGINNER', "Boshlang'ich"), ('INTERMEDIATE', "O'rta"), ('ADVANCED', 'Murakkab')], default='BEGINNER', max_length=20),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='required_camera',
            field=models.BooleanField(default=False, help_text='Require camera access'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='tab_switch_limit',
            field=models.IntegerField(default=3, help_text='Max allowed tab switches before auto-submit'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='time_limit_per_question',
            field=models.IntegerField(default=0, help_text='Seconds per question (0 = no limit)'),
        ),
        migrations.AddField(
            model_name='question',
            name='code_template',
            field=models.TextField(blank=True, help_text='Starter code for CODE questions', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('NUMERIC', 'Numeric Answer'), ('TEXT', 'Text Answer'), ('CODE', 'Code Submission')], default='MCQ', max_length=10),
        ),
        migrations.AddField(
            model_name='testresult',
            name='device_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='status',
            field=models.CharField(default='COMPLETED', max_length=20),
        ),
        migrations.AddField(
            model_name='testresult',
            name='tab_switches_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(help_text='Index for MCQ, number/text for others'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='time_taken',
            field=models.IntegerField(default=0, help_text='Time in seconds'),
        ),
    ]
