# Generated by Django 6.0.1 on 2026-01-27 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_olympiad_cannot_go_back_olympiad_format_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['module__order', 'order']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='duration',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='current_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_learners', to='api.lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_duration',
            field=models.IntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_type',
            field=models.CharField(default='YOUTUBE', max_length=20),
        ),
        migrations.CreateModel(
            name='LessonPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CODE', 'Coding Challenge'), ('MATH', 'Math Problem'), ('TEXT', 'Text Answer'), ('UPLOAD', 'File Upload')], default='TEXT', max_length=20)),
                ('problem_text', models.TextField()),
                ('correct_answer', models.TextField(blank=True, help_text='For auto-checking text/math', null=True)),
                ('test_cases', models.JSONField(blank=True, help_text='For code runner', null=True)),
                ('points', models.IntegerField(default=10)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice', to='api.lesson')),
            ],
            options={
                'db_table': 'lesson_practices',
            },
        ),
        migrations.CreateModel(
            name='LessonTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_pass_score', models.IntegerField(default=70, help_text='Percentage 0-100')),
                ('max_attempts', models.IntegerField(default=3)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='api.lesson')),
                ('questions', models.ManyToManyField(related_name='lesson_tests', to='api.question')),
            ],
            options={
                'db_table': 'lesson_tests',
            },
        ),
        migrations.CreateModel(
            name='LiveLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('meet_link', models.URLField(help_text='Google Meet link')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_lessons', to='api.course')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'live_lessons',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.course')),
            ],
            options={
                'db_table': 'modules',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.module'),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_video_watched', models.BooleanField(default=False)),
                ('video_last_position', models.IntegerField(default=0, help_text='Seconds watched')),
                ('practice_score', models.IntegerField(blank=True, null=True)),
                ('practice_submission', models.TextField(blank=True, null=True)),
                ('test_score', models.IntegerField(blank=True, null=True)),
                ('test_attempts', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='api.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson_progress',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
