# Generated by Django 6.0.1 on 2026-01-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_lesson_options_remove_lesson_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
