# Generated by Django 6.0.1 on 2026-01-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_enrollment_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
    ]
