# Generated by Django 6.0.1 on 2026-01-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('text_uz', models.TextField()),
                ('text_ru', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('REPUBLIC', 'Respublika'), ('REGION', 'Viloyat'), ('SCHOOL', 'Maktab')], default='REPUBLIC', max_length=20)),
                ('student_name', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('position', models.IntegerField(choices=[(1, "1-o'rin"), (2, "2-o'rin"), (3, "3-o'rin")], default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='winners/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='api.subject')),
            ],
            options={
                'db_table': 'winners',
                'ordering': ['-created_at'],
            },
        ),
    ]
