# Generated by Django 6.0.1 on 2026-01-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_testimonial_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageconfig',
            name='show_courses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='show_cta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='show_faq',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='show_mentors',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='show_olympiads',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='show_professions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='show_stats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='show_steps',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='show_testimonials',
            field=models.BooleanField(default=True),
        ),
    ]
