# Generated by Django 6.0.1 on 2026-01-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_homepageconfig_show_courses_homepageconfig_show_cta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='YouTube Video ID (e.g. _GjgFMGQg40)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Direct video URL if not YouTube', null=True),
        ),
    ]
