# Generated by Django 6.0.1 on 2026-01-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_lesson_youtube_id_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
