# Generated by Django 6.0.1 on 2026-01-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_course_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('PENDING', 'Kutilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan')], default='DRAFT', max_length=20),
        ),
    ]
