# Generated by Django 6.0.1 on 2026-01-30 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='allowed_ip_range',
            field=models.CharField(blank=True, help_text='Comma separated IPs or CIDR', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='currency',
            field=models.CharField(default='UZS', max_length=3),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Oson'), ('MEDIUM', "O'rta"), ('HARD', 'Qiyin')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='evaluation_criteria',
            field=models.TextField(blank=True, help_text='HTML/Markdown content'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='grade_range',
            field=models.CharField(blank=True, help_text='e.g. 5-6, 7-9, 10-11', max_length=50),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='max_attempts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='prizes',
            field=models.TextField(blank=True, help_text='HTML/Markdown content'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='required_full_screen',
            field=models.BooleanField(default=False, help_text='Force full screen mode'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='rules',
            field=models.TextField(blank=True, help_text='HTML/Markdown content'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='subject_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olympiads_api', to='api.subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation shown after test'),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=0, help_text='Seconds for this specific question (0=none)'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('UPCOMING', 'Kutilmoqda'), ('ONGOING', 'Jarayonda'), ('PAUSED', "To'xtatilgan"), ('COMPLETED', 'Tugagan'), ('CANCELED', 'Bekor qilingan')], default='DRAFT', max_length=15),
        ),
    ]
