# Generated by Django 6.0.1 on 2026-01-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_olympiad_allowed_ip_range_olympiad_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='disable_copy_paste',
            field=models.BooleanField(default=False, help_text='Disable copy/paste functionality'),
        ),
    ]
