# Generated by Django 6.0.1 on 2026-01-30 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_olympiad_disable_copy_paste'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('UPCOMING', 'Kutilmoqda'), ('ONGOING', 'Jarayonda'), ('PAUSED', "To'xtatilgan"), ('CHECKING', 'Tekshirilmoqda'), ('PUBLISHED', "E'lon qilingan"), ('COMPLETED', 'Tugagan'), ('CANCELED', 'Bekor qilingan')], default='DRAFT', max_length=15),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20),
        ),
    ]
