# Generated by Django 6.0.1 on 2026-01-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_teacherprofile_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.CharField(blank=True, help_text='Template name or path', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_certificate_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='last_accessed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='xp_amount',
            field=models.IntegerField(default=10, help_text='XP awarded for completing this lesson'),
        ),
    ]
