# Generated by Django 6.0.1 on 2026-01-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_course_certificate_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='disqualified_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SYSTEM', 'System Message'), ('PAYMENT', 'Payment Update'), ('ACHIEVEMENT', 'Achievement Unlocked'), ('COURSE', 'Course Status Update')], default='SYSTEM', max_length=20),
        ),
    ]
