# Generated by Django 6.0.1 on 2026-01-30 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_testresult_disqualified_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='career_opportunities',
            field=models.TextField(blank=True, help_text='Qaysi ishlarda ishlash mumkin'),
        ),
        migrations.AddField(
            model_name='profession',
            name='certification_info',
            field=models.TextField(blank=True, help_text='Sertifikat haqida'),
        ),
        migrations.AddField(
            model_name='profession',
            name='learning_time',
            field=models.CharField(blank=True, help_text="O'rganish vaqti", max_length=100),
        ),
        migrations.AddField(
            model_name='profession',
            name='requirements',
            field=models.TextField(blank=True, help_text='Boshlash uchun talablar'),
        ),
        migrations.AddField(
            model_name='profession',
            name='salary_range',
            field=models.CharField(blank=True, help_text='Taxminiy daromad', max_length=100),
        ),
        migrations.AddField(
            model_name='profession',
            name='suitability',
            field=models.TextField(blank=True, help_text='Kimlar uchun mos'),
        ),
        migrations.AddField(
            model_name='professionroadmapstep',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_steps', to='api.course'),
        ),
        migrations.AddField(
            model_name='professionroadmapstep',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserProfessionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FOLLOWING', 'Kuzatmoqda'), ('COMPLETED', 'Tugatgan')], default='FOLLOWING', max_length=20)),
                ('progress_percent', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profession_progress',
                'unique_together': {('user', 'profession')},
            },
        ),
    ]
