# Generated by Django 6.0.1 on 2026-01-30 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_profession_career_opportunities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionsubject',
            name='percentage',
            field=models.IntegerField(default=50, help_text='How much this subject is needed (0-100)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Hide from public if False'),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='professionsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_links', to='api.subject'),
        ),
    ]
