# Generated by Django 6.0.1 on 2026-01-30 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_add_subject_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issued_at']},
        ),
        migrations.AddField(
            model_name='certificate',
            name='cert_type',
            field=models.CharField(choices=[('COURSE', 'Kurs sertifikati'), ('OLYMPIAD', 'Olimpiada sertifikati'), ('DIPLOMA', 'Diplom / Faxriy yorliq')], default='COURSE', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/pdf/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/qr/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Rad etish sababi'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='score',
            field=models.IntegerField(default=0, help_text='Umumiy ball'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='grade',
            field=models.CharField(help_text="98% yoki 1-o'rin", max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('VERIFIED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_certificates', to=settings.AUTH_USER_MODEL),
        ),
    ]
