# Generated by Django 6.0.1 on 2026-01-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_enhance_certificate_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistantFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uz', models.CharField(max_length=255)),
                ('question_ru', models.CharField(max_length=255)),
                ('answer_uz', models.TextField()),
                ('answer_ru', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'Umumiy'), ('COURSES', 'Kurslar'), ('OLYMPIADS', 'Olimpiadalar'), ('PAYMENTS', "To'lovlar")], default='GENERAL', max_length=20)),
                ('action_label_uz', models.CharField(blank=True, max_length=50, null=True)),
                ('action_label_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('action_link', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_assistant_faqs',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
