# Generated by Django 6.0.1 on 2026-01-31 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_aiassistantfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(default='SYSTEM', max_length=20)),
                ('channel', models.CharField(default='WEB', max_length=20)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='last_active_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict, help_text="User's notification preferences"),
        ),
        migrations.CreateModel(
            name='NotificationBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(default='SYSTEM', max_length=20)),
                ('channel', models.CharField(default='WEB', max_length=20)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('audience_type', models.CharField(choices=[('ALL', 'Barcha foydalanuvchilar'), ('STUDENTS', 'Talabalar'), ('TEACHERS', 'Oʻqituvchilar'), ('COURSE_STUDENTS', 'Kurs oʻquvchilari'), ('OLYMPIAD_PARTICIPANTS', 'Olimpiada qatnashchilari'), ('INACTIVE', 'Faol boʻlmaganlar (7+ kun)'), ('NEW', 'Yangi foydalanuvchilar (24+ soat)')], default='ALL', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('IN_PROGRESS', 'Jarayonda'), ('SENT', 'Yuborildi'), ('FAILED', 'Xatolik')], default='PENDING', max_length=20)),
                ('total_recipients', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('olympiad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.olympiad')),
            ],
            options={
                'db_table': 'notification_broadcasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='broadcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_notifications', to='api.notificationbroadcast'),
        ),
    ]
