# Generated by Django 6.0.1 on 2026-01-31 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_notificationtemplate_user_last_active_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiassistantfaq',
            options={'ordering': ['-priority', 'order', '-created_at']},
        ),
        migrations.AddField(
            model_name='aiassistantfaq',
            name='priority',
            field=models.IntegerField(default=0, help_text='Yechimning ustuvorligi'),
        ),
        migrations.AddField(
            model_name='aiassistantfaq',
            name='search_tags',
            field=models.TextField(blank=True, help_text='Qidiruv teglari (vergul bilan)'),
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('context_url', models.CharField(blank=True, max_length=255, null=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_conversations',
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('source', models.CharField(choices=[('FAQ', 'FAQ Match'), ('LLM', 'AI Generated'), ('SYSTEM', 'System')], default='FAQ', max_length=10)),
                ('rating', models.IntegerField(blank=True, help_text='1 for Up, -1 for Down', null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.aiconversation')),
                ('faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.aiassistantfaq')),
            ],
            options={
                'db_table': 'ai_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUnansweredQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('context_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_unanswered_questions',
                'ordering': ['-created_at'],
            },
        ),
    ]
