# Generated by Django 6.0.1 on 2026-02-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_notificationsettings_paymentproviderconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageconfig',
            name='show_winners',
            field=models.BooleanField(default=True),
        ),
    ]
