# Generated by Django 6.0.1 on 2026-02-01 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_olympiad_result_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olympiads', to='api.course'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olympiads', to='api.profession'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
