# Generated by Django 6.0.1 on 2026-02-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_olympiad_course_olympiad_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
