# Generated by Django 6.0.1 on 2026-02-02 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_olympiad_description_alter_olympiad_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympiad',
            name='prizes',
        ),
        migrations.AddField(
            model_name='olympiad',
            name='certificate_config',
            field=models.JSONField(blank=True, help_text='Certificate generation settings', null=True),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='eligibility_grades',
            field=models.JSONField(blank=True, help_text='List of eligible grades, e.g. [7, 8, 9]', null=True),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='eligibility_regions',
            field=models.JSONField(blank=True, help_text='List of eligible regions', null=True),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='technical_config',
            field=models.JSONField(blank=True, help_text='Technical constraints like tab_limit', null=True),
        ),
        migrations.CreateModel(
            name='OlympiadPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='olympiad_prizes/')),
                ('description', models.TextField(blank=True)),
                ('condition', models.CharField(help_text="e.g. '1-o'rin', 'Top 10'", max_length=100)),
                ('value', models.CharField(blank=True, help_text='Monetary value or equivalent', max_length=100)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='api.olympiad')),
            ],
            options={
                'db_table': 'olympiad_prizes',
                'ordering': ['id'],
            },
        ),
    ]
