# Generated by Django 6.0.1 on 2026-02-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_olympiad_prizes_olympiad_certificate_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Premium teachers can create unlimited courses'),
        ),
    ]
