# Generated by Django 6.0.1 on 2026-02-02 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_teacherprofile_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='creation_fee_paid',
            field=models.BooleanField(default=False, help_text='Whether teacher paid course creation fee'),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20)),
                ('payment_method', models.CharField(choices=[('CARD', 'Bank Card'), ('CLICK', 'Click'), ('PAYME', 'Payme')], max_length=50)),
                ('payment_details', models.JSONField(help_text='Card number, phone, account details')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payouts', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Available for withdrawal', max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, help_text='Locked for 7 days after sale', max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, help_text='Lifetime earnings', max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, help_text='Total payouts received', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('COURSE_CREATION_FEE', 'Course Creation Fee'), ('COURSE_SALE', 'Course Sale'), ('COMMISSION', 'Platform Commission'), ('PAYOUT', 'Payout to Teacher'), ('REFUND', 'Refund')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('payment_provider', models.CharField(blank=True, help_text='click, payme, etc', max_length=50, null=True)),
                ('payment_id', models.CharField(blank=True, help_text='External payment ID', max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='creation_fee_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_creation_fees', to='api.transaction'),
        ),
    ]
