# Generated by Django 6.0.1 on 2026-02-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_course_creation_fee_paid_payout_teacherwallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, help_text='Instagram video/reel URL'),
        ),
    ]
