# Generated by Django 6.0.1 on 2026-02-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_add_instagram_url_to_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeCourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(default='MUTLAQO BEPUL', max_length=200)),
                ('title_ru', models.CharField(default='АБСОЛЮТНО БЕСПЛАТНО', max_length=200)),
                ('subtitle_uz', models.CharField(default="O'rganishni hoziroq boshlang", max_length=300)),
                ('subtitle_ru', models.CharField(default='Начните учиться прямо сейчас', max_length=300)),
                ('description_uz', models.TextField(default="Hech qanday to'lovsiz, ro'yxatdan o'tmasdan ham ko'rishingiz mumkin bo'lgan darslar.")),
                ('description_ru', models.TextField(default='Уроки, которые вы можете посмотреть без какой-либо оплаты, даже без регистрации.')),
                ('button_text_uz', models.CharField(default='Barcha bepul darslar', max_length=100)),
                ('button_text_ru', models.CharField(default='Все бесплатные уроки', max_length=100)),
                ('button_link', models.CharField(default='/courses?filter=free', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Free Course Section',
                'verbose_name_plural': 'Free Course Sections',
                'db_table': 'free_course_section',
                'ordering': ['order'],
            },
        ),
    ]
