# Generated by Django 6.0.1 on 2026-02-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_freecoursesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeCourseLessonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200)),
                ('category_uz', models.CharField(default="Boshlang'ich", max_length=100)),
                ('category_ru', models.CharField(default='Начальный', max_length=100)),
                ('image', models.URLField(help_text='Image URL for the course card', max_length=500)),
                ('duration_minutes', models.IntegerField(default=30, help_text='Duration in minutes')),
                ('link', models.CharField(default='/auth/register', help_text='Link when card is clicked', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Free Course Lesson Card',
                'verbose_name_plural': 'Free Course Lesson Cards',
                'db_table': 'free_course_lesson_cards',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
