# Generated by Django 6.0.1 on 2026-02-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_add_default_free_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
