# Generated by Django 6.0.1 on 2026-02-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_payment_reference_id_alter_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='click_merchant_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='humo_bot_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='unique_add',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='admin_chat_id',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
