# Generated by Django 6.0.1 on 2026-02-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_botconfig_click_merchant_id_botconfig_humo_bot_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentproviderconfig',
            old_name='extra_config',
            new_name='config',
        ),
        migrations.AddField(
            model_name='paymentproviderconfig',
            name='name',
            field=models.CharField(default='Payment Provider', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentproviderconfig',
            name='type',
            field=models.CharField(choices=[('INTEGRATION', 'Integration'), ('MANUAL', 'Manual'), ('BOT', 'Bot')], default='INTEGRATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentproviderconfig',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentproviderconfig',
            name='provider',
            field=models.CharField(choices=[('CLICK', 'Click'), ('PAYME', 'Payme'), ('UZUM', 'Uzum'), ('CARD', 'Card Transfer'), ('QR', 'QR Code'), ('USERBOT', 'User Bot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentproviderconfig',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
