# Generated by Django 6.0.1 on 2026-02-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_rename_extra_config_paymentproviderconfig_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='active_payment_type',
            field=models.CharField(choices=[('INTEGRATION', 'Automatic Integration'), ('MANUAL', 'Manual Payment'), ('BOT', 'User Bot')], default='INTEGRATION', help_text='Which payment method type is currently active for users.', max_length=20),
        ),
    ]
