# Generated by Django 6.0.1 on 2026-02-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_platformsettings_active_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='ardcoin_exchange_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text="1 ArdCoin = necha so'm?", max_digits=10),
        ),
    ]
