# Generated by Django 6.0.1 on 2026-02-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_payment_receipt_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_message_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
