# Generated by Django 6.0.1 on 2026-02-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_payment_admin_message_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageconfig',
            name='teaser_button_link',
            field=models.CharField(default='/auth/register', max_length=200),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='teaser_button_text_ru',
            field=models.CharField(default='Узнать больше', max_length=50),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='teaser_button_text_uz',
            field=models.CharField(default="Xabardor bo'lish", max_length=50),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='teaser_image',
            field=models.ImageField(blank=True, help_text="Tavsiya etilgan o'lcham: 1200x400px. Format: JPG, PNG.", null=True, upload_to='homepage/teaser/'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='teaser_subtitle_ru',
            field=models.TextField(default='Изучайте современные профессии. Мы активно работаем над нашими новыми курсами.'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='teaser_subtitle_uz',
            field=models.TextField(default="Zamonaviy kasblarni o'rganing. Yangi kurslarimiz ustida qizg'in ish olib boryapmiz."),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='teaser_title_ru',
            field=models.CharField(default='Искусственный Интеллект и Data Science', max_length=200),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='teaser_title_uz',
            field=models.CharField(default="Sun'iy Intellekt va Data Science", max_length=200),
        ),
    ]
