# Generated by Django 6.0.1 on 2026-02-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_homepageconfig_teaser_button_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='humo_bot_url',
            field=models.CharField(blank=True, default='https://t.me/ardentsoft_olimpiada_bot', max_length=255, null=True),
        ),
    ]
