# Generated by Django 6.0.1 on 2026-02-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_botconfig_humo_bot_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='admin_chat_id',
            field=models.CharField(default='0', help_text='Comma separated admin chat IDs', max_length=500),
        ),
    ]
