# Generated by Django 6.0.1 on 2026-02-16 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_botconfig_admin_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text='1, 2 or 3')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONTACTED', 'Contacted'), ('ADDRESS_RECEIVED', 'Address received'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners_prizes', to='api.olympiad')),
                ('prize_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.olympiadprize')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_prizes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'winner_prizes',
                'ordering': ['position'],
                'unique_together': {('olympiad', 'student')},
            },
        ),
        migrations.CreateModel(
            name='PrizeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prize', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.winnerprize')),
            ],
            options={
                'db_table': 'prize_addresses',
            },
        ),
    ]
