# Generated by Django 6.0.1 on 2026-02-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_course_admin_course_platform_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='registration_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='registration_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('UPCOMING', 'Kutilmoqda'), ('REGISTRATION_OPEN', "Ro'yxatdan o'tish ochiq"), ('ONGOING', 'Jarayonda'), ('PAUSED', "To'xtatilgan"), ('CHECKING', 'Tekshirilmoqda'), ('PUBLISHED', "E'lon qilingan"), ('COMPLETED', 'Tugagan'), ('CANCELED', 'Bekor qilingan')], default='DRAFT', max_length=30),
        ),
    ]
