# Generated by Django 6.0.1 on 2026-02-19 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_update_olympiad_status_choices_to_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='primary_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professions_featured', to='api.subject'),
        ),
        migrations.AddField(
            model_name='profession',
            name='required_xp',
            field=models.IntegerField(default=0, help_text='Kasbni ochish uchun kerakli XP'),
        ),
        migrations.AddField(
            model_name='professionroadmapstep',
            name='olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_steps', to='api.olympiad'),
        ),
        migrations.AddField(
            model_name='professionroadmapstep',
            name='required_xp',
            field=models.IntegerField(default=0, help_text='Ushbu qadam uchun kerakli XP'),
        ),
        migrations.AlterField(
            model_name='professionroadmapstep',
            name='step_type',
            field=models.CharField(choices=[('LEARN', "O'rganish"), ('PRACTICE', 'Amaliyot'), ('COMPETE', 'Olimpiada'), ('PROJECT', 'Loyiha'), ('CERTIFY', 'Sertifikat')], default='LEARN', max_length=20),
        ),
    ]
