# Generated by Django 6.0.1 on 2026-02-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_profession_primary_subject_profession_required_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='xp_reward',
            field=models.IntegerField(default=30, help_text='XP awarded for completing all lessons in this module'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='winner_xp',
            field=models.IntegerField(default=400, help_text='Extra XP for 1st place/Winners'),
        ),
        migrations.AlterField(
            model_name='course',
            name='xp_reward',
            field=models.IntegerField(default=100, help_text='XP given upon completion'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='xp_reward',
            field=models.IntegerField(default=150, help_text='XP given for participation (finishing test)'),
        ),
    ]
