# Generated by Django 6.0.1 on 2026-02-20 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_module_xp_reward_olympiad_winner_xp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympiadprize',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='olympiadprize',
            name='value',
        ),
        migrations.AddField(
            model_name='course',
            name='completion_min_progress',
            field=models.IntegerField(default=80, help_text='Kurs tugallandi hisoblash uchun minimal foiz'),
        ),
        migrations.AddField(
            model_name='course',
            name='lock_strategy',
            field=models.CharField(choices=[('free', 'Erkin (barcha darslar ochiq)'), ('sequential', 'Ketma-ket (oldingi tugaguncha keyingisi yopiq)'), ('custom', 'Maxsus (har darsda belgilangan)')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_locked',
            field=models.BooleanField(default=False, help_text="Agar True bo'lsa, oldingi dars tugaguncha yopiq"),
        ),
        migrations.AddField(
            model_name='lesson',
            name='required_lesson',
            field=models.ForeignKey(blank=True, help_text='Bu dars tugamasdan yuqoridagi dars ochilmaydi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks_lessons', to='api.lesson'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='auto_reward',
            field=models.BooleanField(default=False, help_text='Olimpiada tugagach sovrinlarni avto yuborish'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='reward_distribution_status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('IN_PROGRESS', 'Jarayonda'), ('COMPLETED', 'Yakunlandi'), ('FAILED', 'Xatolik')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='reward_strategy',
            field=models.CharField(choices=[('TOP_N', "Top g'oliblar bo'yicha"), ('THRESHOLD', "Ball foizi bo'yicha"), ('MANUAL', "Qo'lda")], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='olympiadprize',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Coin yoki XP miqdori', max_digits=12),
        ),
        migrations.AddField(
            model_name='olympiadprize',
            name='prize_type',
            field=models.CharField(choices=[('PHYSICAL', 'Fizik sovrin (Medal, Kitob...)'), ('COIN', 'Ardent Coin'), ('XP', 'Tajriba balli (XP)')], default='PHYSICAL', max_length=20),
        ),
        migrations.AddField(
            model_name='olympiadprize',
            name='target_value',
            field=models.IntegerField(default=1, help_text="1-o'rin uchun 1, yoki Threshold uchun ball foizi (80, 90...)"),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('COURSE_CREATION_FEE', 'Course Creation Fee'), ('COURSE_SALE', 'Course Sale'), ('COMMISSION', 'Platform Commission'), ('PAYOUT', 'Payout to Teacher'), ('REFUND', 'Refund'), ('OLYMPIAD_REWARD', 'Olympiad Reward'), ('STREAK_REWARD', 'Streak Reward')], max_length=30),
        ),
    ]
