# Generated by Django 6.0.1 on 2026-02-20 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_lesson_lock_fields_course_lock_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.olympiad'),
        ),
    ]
