# Generated by Django 6.0.1 on 2026-02-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_alter_question_olympiad'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='required_final_score',
            field=models.IntegerField(default=70, help_text='Sertifikat olish uchun yakuniy imtihondan kutilayotgan minimal ball'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='min_watch_percent',
            field=models.IntegerField(default=80, help_text="Dars tugallangan hisoblanishi uchun minimal ko'rish foizi"),
        ),
        migrations.AddField(
            model_name='lessontest',
            name='is_final',
            field=models.BooleanField(default=False, help_text="Agar True bo'lsa, bu kursning yakuniy imtihoni hisoblanadi"),
        ),
    ]
