# Generated by Django 6.0.1 on 2026-02-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_course_required_final_score_lesson_min_watch_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='identity_document',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_docs/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_identity_verified',
            field=models.BooleanField(default=False),
        ),
    ]
