# Generated by Django 6.0.1 on 2026-02-21 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_teacherprofile_identity_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_internal',
            field=models.BooleanField(default=False, help_text="Platformaning o'z kursi"),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teacher_type',
            field=models.CharField(choices=[('NORMAL', 'Oddiy'), ('VIP', 'VIP'), ('INTERNAL', 'Internal (Platforma)')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='vip_expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VIPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_type', models.CharField(max_length=20)),
                ('new_type', models.CharField(max_length=20)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_vips', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vip_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
