# Generated by Django 6.0.1 on 2026-02-22 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_course_is_internal_lesson_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_commission', models.DecimalField(decimal_places=2, default=30.0, help_text='Normal teachers platform %', max_digits=5)),
                ('vip_commission', models.DecimalField(decimal_places=2, default=20.0, help_text='VIP teachers platform %', max_digits=5)),
                ('internal_commission', models.DecimalField(decimal_places=2, default=10.0, help_text='Internal teachers platform %', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Commission Settings',
                'db_table': 'commission_settings',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='is_paid_creation',
            field=models.BooleanField(default=False, help_text='Whether this course requires a creation fee'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'TEACHER'}, related_name='co_teaching_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='checker',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checking_olympiads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='creation_fee_paid',
            field=models.BooleanField(default=False, help_text='Whether teacher paid olympiad creation fee'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='creation_fee_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olympiad_creation_fees', to='api.transaction'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='is_paid_creation',
            field=models.BooleanField(default=False, help_text='Whether this olympiad requires a creation fee'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='moderator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_olympiads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_lifetime_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='teacher_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
