# Generated by Django 6.0.1 on 2026-02-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_commissionsettings_course_is_paid_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('PENDING', 'Kutilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('REGISTRATION_OPEN', "Ro'yxatga olish boshlandi"), ('REGISTRATION_CLOSED', "Ro'yxatdan o'tish tugadi"), ('ONGOING', 'Olimpiada boshladi'), ('CHECKING', 'Tekshirilmoqda'), ('PUBLISHED', "Natijalar e'lon qilindi")], default='DRAFT', max_length=30),
        ),
    ]
