# Generated by Django 6.0.1 on 2026-02-23 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_alter_olympiad_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='prestige_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profession',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='total_required_xp',
            field=models.IntegerField(default=0, help_text='Kasb uchun umumiy talab qilingan XP'),
        ),
        migrations.CreateModel(
            name='ProfessionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('unlock_xp', models.IntegerField(default=0, help_text='Ushbu levelni ochish uchun talab etiladigan XP')),
                ('order', models.IntegerField(default=0)),
                ('is_prestige_only', models.BooleanField(default=False)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='api.profession')),
            ],
            options={
                'db_table': 'profession_levels',
                'ordering': ['profession', 'order', 'level_number'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('node_type', models.CharField(choices=[('course', 'Course'), ('olympiad', 'Olympiad'), ('project', 'Project'), ('exam', 'Exam'), ('certificate', 'Certificate'), ('custom', 'Custom Task')], default='course', max_length=20)),
                ('reference_id', models.IntegerField(blank=True, help_text='Course/Olympiad/etc ID', null=True)),
                ('is_required', models.BooleanField(default=True, help_text='Ushbu bosqich majburiymi?')),
                ('xp_reward', models.IntegerField(default=0, help_text='Ushbu qadamni yakunlash uchun beriladigan XP')),
                ('unlock_condition', models.JSONField(blank=True, help_text='Shartlar (min_score, required_nodes, etc.)', null=True)),
                ('order', models.IntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.professionlevel')),
            ],
            options={
                'db_table': 'profession_nodes',
                'ordering': ['level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserNodeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='api.professionnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_node_progress',
                'unique_together': {('user', 'node')},
            },
        ),
        migrations.CreateModel(
            name='UserProfessionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('active', 'Active'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.professionlevel')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='api.profession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profession_states',
                'unique_together': {('user', 'profession')},
            },
        ),
    ]
