# Generated by Django 6.0.1 on 2026-02-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_profession_prestige_only_profession_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='feedback',
            field=models.TextField(blank=True, help_text="Teacher's feedback for the student", null=True),
        ),
    ]
